version: "3.9"
services:
  server:
    build:
      context: ./server
      args:
        EXPOSE_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/server
    environment:
      PORT: ${SERVER_PORT}
