version: "3.9"
services:
  server:
    build:
      context: ./server
      args:
        EXPOSE_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/server
    environment:
      PORT: ${SERVER_PORT}
    networks:
      - sequel
  database:
    container_name: "sequel-db"
    image: postgres:14.5
    environment:
      POSTGRES_USER: "sequel_admin"
      POSTGRES_PASSWORD: "sequel"
      POSTGRES_DB: "sequel"
      PG_DATA: /var/lib/postgresql/data
    networks:
      - sequel
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  caching:
    container_name: "sequel_caching"
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./helpers/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - sequel
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - sequel
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  
    networks:
      - sequel
volumes:
  postgres-data:
  redis-data:
  mongo-data:

networks:
  sequel: